# Generated by Django 5.2.6 on 2025-09-30 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("edibles", "0004_alter_edible_ingredients"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("BREAKFAST", "Breakfast"),
                            ("LUNCH", "Lunch"),
                            ("DINNER", "Dinner"),
                            ("SNACK", "Snack"),
                        ],
                        max_length=20,
                    ),
                ),
                ("eaten_at", models.DateTimeField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "edibles",
                    models.ManyToManyField(
                        blank=True, related_name="used_in_meals", to="edibles.edible"
                    ),
                ),
            ],
        ),
    ]
