# Generated by Django 5.2.4 on 2025-08-08 17:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0001_initial"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        # No operations needed - models were moved to recipes app
    ]
