# Generated by Django 5.2.4 on 2025-08-08 17:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0002_remove_recipeingredient_ingredient_and_more"),
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meal",
            name="recipes",
            field=models.ManyToManyField(
                blank=True, related_name="meals", to="recipes.recipe"
            ),
        ),
    ]
