# Generated by Django 5.2.4 on 2025-08-08 17:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("meals", "0003_auto_20250808_1726"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recipeingredient",
            name="ingredient",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="ingredients",
        ),
        migrations.RemoveField(
            model_name="recipeingredient",
            name="recipe",
        ),
        migrations.AlterUniqueTogether(
            name="recipeingredient",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
        migrations.DeleteModel(
            name="Recipe",
        ),
        migrations.DeleteModel(
            name="RecipeIngredient",
        ),
    ]
