services:
  web:
    image: cevaude/foodmood:latest
    ports:
      - "${PROD_PORT}:8000"
    restart: always
    environment:
      - DJANGO_DEBUG=false
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-foodmood}
      - POSTGRES_USER=${POSTGRES_USER:-foodmood}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - db_foodmood:/var/lib/postgresql/data/

volumes:
  db_foodmood:
