services:
  web:
    restart: always
    environment:
      - DJANGO_DEBUG=false
    volumes: []  # Remove development volume mounts
    command: gunicorn --config ../gunicorn.conf.py foodmood.wsgi:application

  db:
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-foodmood}
      - POSTGRES_USER=${POSTGRES_USER:-foodmood}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports: []  # Remove port exposure in production
