services:
  web:
    image: cevaude/foodmood:latest
    ports:
      - "${PROD_PORT:-8000}:8000"
    restart: always
    environment: []

  db:
    image: postgres:16-alpine
    restart: always
    environment: []
    volumes:
      - db_foodmood:/var/lib/postgresql/data/

volumes:
  db_foodmood:
