services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY:-your-secret-key-here}
      - DJANGO_DEBUG=true
    working_dir: /app/foodmood
    restart: unless-stopped
    command: bash ../scripts/entrypoint.dev.sh
