# Generated by Django 5.2.6 on 2025-11-03 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WellbeingCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="WellbeingOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=64)),
                ("value", models.IntegerField()),
                ("color", models.CharField(blank=True, max_length=20)),
                ("order", models.IntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="wellbeing.wellbeingcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "value"],
                "unique_together": {("category", "label"), ("category", "value")},
            },
        ),
        migrations.CreateModel(
            name="WellbeingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(blank=True, max_length=512)),
                ("recorded_at", models.DateTimeField()),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="wellbeing.wellbeingcategory",
                    ),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="wellbeing.wellbeingoption",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wellbeing entries",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["recorded_at"], name="wellbeing_w_recorde_7fc17b_idx"
                    ),
                    models.Index(
                        fields=["category", "recorded_at"],
                        name="wellbeing_w_categor_88c667_idx",
                    ),
                ],
            },
        ),
    ]
