# Generated by Django 5.2.4 on 2025-07-28 08:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WellbeingParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the parameter (e.g., 'Energy Level', 'Mood', 'Stomach Comfort')",
                        max_length=200,
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("categoric", "Categoric"), ("numeric", "Numeric")],
                        help_text="Type of the parameter: categoric or numeric",
                        max_length=20,
                    ),
                ),
                (
                    "options",
                    models.JSONField(
                        blank=True,
                        help_text="Array of available options (only for categoric parameters)",
                        null=True,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of what this parameter tracks",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                ("update_date", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who created this parameter",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing_parameters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WellbeingEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoric_value",
                    models.CharField(
                        blank=True,
                        help_text="The value, if it is a categoric parameter",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "numeric_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="The value, if it is a numeric parameter",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "date_time",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="When this entry was logged",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Optional notes about this entry"
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who logged this entry",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wellbeing_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parameter",
                    models.ForeignKey(
                        help_text="The wellbeing parameter this entry is for",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="wellbeing.wellbeingparameter",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Wellbeing entries",
                "ordering": ["-date_time"],
            },
        ),
        migrations.AddIndex(
            model_name="wellbeingparameter",
            index=models.Index(fields=["user"], name="wellbeing_w_user_id_f57184_idx"),
        ),
        migrations.AddIndex(
            model_name="wellbeingparameter",
            index=models.Index(fields=["type"], name="wellbeing_w_type_1a7cd6_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="wellbeingparameter",
            unique_together={("user", "name")},
        ),
        migrations.AddIndex(
            model_name="wellbeingentry",
            index=models.Index(fields=["user"], name="wellbeing_w_user_id_f3573e_idx"),
        ),
        migrations.AddIndex(
            model_name="wellbeingentry",
            index=models.Index(
                fields=["parameter"], name="wellbeing_w_paramet_6d5d24_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellbeingentry",
            index=models.Index(
                fields=["date_time"], name="wellbeing_w_date_ti_91902b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="wellbeingentry",
            index=models.Index(
                fields=["user", "date_time"], name="wellbeing_w_user_id_896a35_idx"
            ),
        ),
    ]
