# Generated by Django 5.2.6 on 2025-11-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellbeing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wellbeingcategory",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
