# Generated by Django 5.2.4 on 2025-08-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wellbeing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wellbeingentry",
            name="categoric_value",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The value, if it is a categoric parameter",
                max_length=200,
            ),
            preserve_default=False,
        ),
    ]
