# Generated by Django 5.2.4 on 2025-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edibles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="edible",
            name="ingredients",
            field=models.ManyToManyField(related_name="used_in", to="edibles.edible"),
        ),
        migrations.DeleteModel(
            name="Ingredient",
        ),
    ]
