# Generated by Django 5.2.4 on 2025-08-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edibles", "0002_edible_ingredients_delete_ingredient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edible",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
