# Generated by Django 5.2.4 on 2025-08-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("edibles", "0003_alter_edible_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="edible",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="used_in", to="edibles.edible"
            ),
        ),
    ]
